<!DOCTYPE html PUBLIC " -//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<title>phone-login</title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap-responsive.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/style.css"/>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-1.9.1.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/effect.js"></script>
</head>
<body>
    <div class="head">
        <div class="logo">
            <a href="#" class="logo-left"><img src="image/logo-left.png" /></a>
            <a href="#" class="logo-right"><img src="image/logo-right.png" /></a>
        </div>
    </div>
    <div class="content content-login">
        <div class="phone-hover">
            <a href="#" class="cur">手机注册</a>
            <a href="#">邮箱注册</a>
        </div>
        <form class="searchbox" action="/wx/public/wx/userregister/register" method="post">
			<input type="hidden" name="type" value="1"/>
            <p>
                <span>手机号码:</span><input type="text" name="mobile" />
            </p> 
            <p>
                <span><label>密</label><font>码:</font></span><input type="password" name="password" />
            </p>
            <p>
                <span>确认密码:</span><input type="password" />
            </p>
            <p>
                <span>动态密码:</span>
                <input type="password" class="dynamic-password" />
                <a href="#" class="phone-button">动态码</a>
            </p>
            <p>
                <input type="checkbox" class="phone-checkbox" />
                <strong>我同意</strong>
                <a href="#" class="phone-deal">企业社区软件许服务可协议</a>
            </p>
            <p>    
                <input type="submit" value="确认" class="phone-submit" />
            </p>
        </form>
        <form class="searchbox searchbox-email" action="/wx/public/wx/userregister/register" method="post">
            <p>
                <span>邮箱:</span><input type="text" name="email"/>
            </p> 
            <p>
                <span><label>密</label><font>码:</font></span><input type="password" name="password" />
            </p>
            <p>
                <span>确认密码:</span><input type="password" />
            </p>
            <p>
                <input type="checkbox" class="phone-checkbox" />
                <strong>我同意</strong>
                <a href="#" class="phone-deal">企业社区软件许服务可协议</a>
            </p>
            <p>    
                <input type="submit" value="确认" class="phone-submit" />
            </p>
        </form>
    </div>
    <div class="foot foot-desktop">
        <a href="phone-desktop.html" target='_blank' class="foot-morning desktop-morning"><img src="<?php echo $this->baseUrl(); ?>/image/foot-morning.png" /></a>
        <a href="phone-desktop.html" target='_blank' class="foot-square foot-shade-square"><img src="<?php echo $this->baseUrl(); ?>/image/foot-shade-square.jpg" /></a>
        <a href="phone-desktop.html" target='_blank' class="foot-triangle-left"><img src="<?php echo $this->baseUrl(); ?>/image/foot-triangle-left.png" /></a>
        <a href="#" class="foot-triangle foot-triangle-right"><img src="<?php echo $this->baseUrl(); ?>/image/foot-triangle.png" /></a>
        <a href="#" class="foot-people foot-white-people"><img src="<?php echo $this->baseUrl(); ?>/image/foot-white-people.png" /></a>
        <span class="circle desktop-circle"><img src="<?php echo $this->baseUrl(); ?>/image/foot-circle.png" /></span>
        <span><img src="<?php echo $this->baseUrl(); ?>/image/foot-circle.png" /></span>
        <span><img src="<?php echo $this->baseUrl(); ?>/image/foot-circle.png" /></span>
    </div>
</body>
</html> 