<!DOCTYPE html PUBLIC " -//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<title>phone-desktop</title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap-responsive.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/style.css"/>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-1.9.1.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/effect.js"></script>
</head>
<body>
    <div class="head">
        <div class="logo">
            <a href="#" class="logo-left"><img src="<?php echo $this->baseUrl(); ?>/image/logo-left.png" /></a>
            <a href="#" class="logo-right"><img src="<?php echo $this->baseUrl(); ?>/image/logo-right.png" /></a>
        </div>
    </div>
    <div class="content content-desktop">
        <ul class="desktop">
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-mcenter.jpg" /></strong><span>M CENTER</span></a>
            </li>
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-price.jpg" /></strong><span>品牌价值</span></a>
            </li>
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-message.jpg" /></strong><span>产品信息</span></a>
            </li>
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-news.jpg" /></strong><span>新闻</span></a>
            </li>
        </ul>
        <ul class="desktop">
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-client.jpg" /></strong><span>我们的客户</span></a>
            </li>
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-exercise.jpg" /></strong><span>活动</span></a>
            </li>
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-sales.jpg" /></strong><span>最新促销</span></a>
            </li>
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-shop.jpg" /></strong><span>店铺</span></a>
            </li>
        </ul>
        <ul class="desktop">
            <li>
               <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-sell.jpg" /></strong><span>在线促销</span></a>
            </li>
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-encyclopedia.jpg" /></strong><span>百科常识</span></a>
            </li>
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-member.jpg" /></strong><span>会员专区</span></a>
            </li>
            <li>  
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-made.jpg" /></strong><span>定制专区</span></a>
            </li>
        </ul>
        <ul class="desktop">
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-recommend.jpg" /></strong><span>热点推荐</span></a>
            </li>
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-arrange.jpg" /></strong><span>日程安排</span></a>
            </li>
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-vip.jpg" /></strong><span>VIP专区</span></a>
            </li>
            <li>
                <a href="#"><strong><img src="<?php echo $this->baseUrl(); ?>/image/content-contact.jpg" /></strong><span>联系我们</span></a>
            </li>
        </ul>
    </div>
    <div class="foot foot-desktop">
        <a href="#" class="foot-morning desktop-morning"><img src="<?php echo $this->baseUrl(); ?>/image/foot-morning.png" /></a>
        <a href="#" class="foot-square foot-shade-square"><img src="<?php echo $this->baseUrl(); ?>/image/foot-shade-square.jpg" /></a>
        <a href="#" class="foot-triangle-left"><img src="<?php echo $this->baseUrl(); ?>/image/foot-triangle-left.png" /></a>
        <a href="#" class="foot-triangle foot-triangle-right"><img src="<?php echo $this->baseUrl(); ?>/image/foot-triangle.png" /></a>
        <a href="#" class="foot-people foot-white-people"><img src="<?php echo $this->baseUrl(); ?>/image/foot-white-people.png" /></a>
        <span class="circle desktop-circle"><img src="<?php echo $this->baseUrl(); ?>/image/foot-circle.png" /></span>
        <span><img src="<?php echo $this->baseUrl(); ?>/image/foot-circle.png" /></span>
        <span><img src="<?php echo $this->baseUrl(); ?>/image/foot-circle.png" /></span>
    </div>
</body>
</html> 


