<!DOCTYPE html PUBLIC " -//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<title>phone-m-center</title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap-responsive.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/style.css"/>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-1.9.1.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/effect.js"></script>
</head>
<body>
    <div class="head">
        <div class="logo">
            <a href="#" class="logo-left"><img src="<?php echo $this->baseUrl(); ?>/image/logo-left.png" /></a>
            <a href="#" class="logo-right"><img src="<?php echo $this->baseUrl(); ?>/image/logo-right.png" /></a>
        </div>
    </div> 
    <div class="content m-center">
        <a href="#"><img src="<?php echo $this->baseUrl(); ?>/image/content-yellow.jpg" alt=""/></a>
        <a href="#"><img src="<?php echo $this->baseUrl(); ?>/image/content-light-red.jpg" alt=""></a>
        <a href="#"><img src="<?php echo $this->baseUrl(); ?>/image/content-light-blue.jpg" alt=""></a>
        <a href="#"><img src="<?php echo $this->baseUrl(); ?>/image/content-purple.jpg" alt=""></a>
        <a href="#"><img src="<?php echo $this->baseUrl(); ?>/image/content-blue.jpg" alt=""></a>
        <a href="#"><img src="<?php echo $this->baseUrl(); ?>/image/content-coffee.jpg" alt=""></a>
        <a href="#"><img src="<?php echo $this->baseUrl(); ?>/image/content-pink.jpg" alt=""></a>
        <a href="#"><img src="<?php echo $this->baseUrl(); ?>/image/content-gray.jpg" alt=""></a>
        <a href="#"><img src="<?php echo $this->baseUrl(); ?>/image/content-green.jpg" alt=""></a>
        <a href="#"><img src="<?php echo $this->baseUrl(); ?>/image/content-orange.jpg" alt=""></a>
        <a href="#"><img src="<?php echo $this->baseUrl(); ?>/image/content-light-green.jpg" alt=""></a>
        <a href="#"><img src="<?php echo $this->baseUrl(); ?>/image/content-red.jpg" alt=""></a>
    </div>
    <div class="foot">
        <a href="#" class="foot-morning"><img src="<?php echo $this->baseUrl(); ?>/image/foot-morning.png" /></a>
        <a href="#" class="foot-square"><img src="<?php echo $this->baseUrl(); ?>/image/foot-square.png" /></a>
        <a href="#" class="foot-triangle-left"><img src="<?php echo $this->baseUrl(); ?>/image/foot-triangle-left.png" /></a>
        <a href="#" class="foot-triangle"><img src="<?php echo $this->baseUrl(); ?>/image/foot-triangle.png" /></a>
        <a href="#" class="foot-people"><img src="<?php echo $this->baseUrl(); ?>/image/foot-people.png" /></a>
        <span class="circle"><img src="<?php echo $this->baseUrl(); ?>/image/foot-circle.png" /></span>
        <span><img src="<?php echo $this->baseUrl(); ?>/image/foot-circle.png" /></span>
        <span><img src="<?php echo $this->baseUrl(); ?>/image/foot-circle.png" /></span>
    </div>
</body>
</html>


