<?php 
/******************************************************
 * Website: http://www.plazathemes.com
*******************************************************/
?> 
<?php if($this->getConfig('enabled')){ ?>	  <!-- start enable -->
	<?php $cur_store = Mage::app()->getStore()->getId() ?>
	<div class="ma-banner8-container">
        <!--<div class="container">-->
	        <div class="flexslider ma-nivoslider">
        <div class="ma-loading"></div>
		<div id="ma-inivoslider" class="slides">
			
				<?php
					// Get data banner
					$slide = $this->getDataBanner8();
					$path = Mage::getBaseUrl('media');					
					$qty_Item = $this->getConfig('qty_item');
					if ($this->getConfig('auto')) { $auto = 'true'; } else { $auto = 'false'; }
					/* Get max item & qty item */
					if ($qty_Item > count($slide)) {
						$qty_Item = count($slide);
					}
				?>
				<?php
					$i = 1;
					foreach($slide as $s) {
						if($i <= $qty_Item) {
							//Get images slide show
							$st1 = $s['image'];
							$p1 = strpos($st1,'banner8');
							$st2 = substr($st1,$p1+7);
							$p2 = strpos($st2,'"');
							$imag = substr($st2,0,$p2);
					?>
					<img style="display: none;"  src="<?php echo $path.'magentothem/banner8'.$imag;?>" alt="" title="#banner8-caption<?php echo $i; ?>"  />
					<?php $i++; ?>
				<?php
                        }//end if
                    } // end foreach
				?>
		</div>
				<?php
					if($this->getConfig('description')) {
						$i = 1;
						foreach($slide as $s) { ?>

								<div id="banner8-caption<?php echo $i; ?>" class="banner8-caption nivo-html-caption nivo-caption">
									<div class="banner8-title">
										<h3><?php echo $this->__($s['title']) ?></h3>
									</div>
									<div class="banner8-des">
										<?php echo $this->__($s['description']) ?>
									</div>
									<?php if( $s['link'] ) { ?>
										<div class="banner8-readmore">
											<a href="<?php echo $s['link']?>" title="<?php echo $this->__('Read more') ?>"><?php echo $this->__('Read more') ?></a>	
										</div>
									<?php } ?>
								</div>						
					<?php
						$i++;
						}
					}
				?>
		<script type="text/javascript">
            $jq(window).load(function() {
                $jq('#ma-inivoslider').nivoSlider({
				  effect: '<?php echo $this->getConfig('animation') ?>',
                    slices: 15,
                    boxCols: 8,
                    boxRows: 4,
                    animSpeed: <?php echo $this->getConfig('interval') ?>,
                    pauseTime: <?php echo $this->getConfig('speed') ?>,
                    startSlide: 0,
					<?php if (!$this->getConfig('nav_ctrl')) { ?>
					controlNav: false,
					<?php } ?>
					<?php if (!$this->getConfig('next_back')) { ?>
					directionNav: false,
					<?php } ?>
                    controlNavThumbs: false,
                    pauseOnHover: true,
                    manualAdvance: false,
                    prevText: 'Prev',
                    nextText: 'Next',
                    afterLoad: function(){
                        $jq('.ma-loading').css("display","none");
                        },     
                    beforeChange: function(){ 
                        $jq('.banner8-title, .banner8-des').css("left","-2000px" );
                        $jq('.banner8-readmore').css("left","-2000px"); 
                    }, 
                    afterChange: function(){ 
                        $jq('.banner8-title, .banner8-des, .banner8-readmore').css("left","40px") 
                    }
                });
            });
		</script>
	</div>
        <!--</div>-->
	</div>
<?php } ?> <!-- end enable -->