<li>
                                <div class="newsListBox">
                                    <h4><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h4>
                                    <p class="newsViewText">[field:description function="cn_substr(@me,100)"/]...</p>
                                    <p class="newsViewFoot"><a href="[field:arcurl/]" target="_blank" class="newsListView">Detail</a>
                                    </p>
                                </div>
                            </li>