<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/141206/1-1412061P040.png ",93,246);
$z[1][4]['ddimg']="/uploads/allimg/141206/1-1412061P040.png";
$z[1][4]['text']="案例";
$z[1][4]['width']="1200";
$z[1][4]['height']="1990";
$z[2]=Array("img"," /uploads/allimg/141206/1-1412061P549.jpg ",248,395);
$z[2][4]['ddimg']="/uploads/allimg/141206/1-1412061P549.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1980";
$z[2][4]['height']="2405";

?>