<?php
$z[0]=Array("field","",819,838);
$z[0][4]['name']="title";
$z[1]=Array("global","",839,865);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",910,932);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",976,1028);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1905,1946);
$z[4][4]['filename']="head_works.htm";
$z[5]=Array("field","",2266,2285);
$z[5][4]['name']="title";
$z[6]=Array("field","",2306,2362);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[7]=Array("field","",2388,2415);
$z[7][4]['name']="phpurl";
$z[8]=Array("field","",2439,2462);
$z[8][4]['name']="id";
$z[9]=Array("field","",2467,2491);
$z[9][4]['name']="mid";
$z[10]=Array("field","\r\n                       <p><img src=\"[field:imgsrc/]\" alt=\"[field:alttext /]\"></p>\r\n					   <br>\r\n					 ",2614,2781);
$z[10][4]['name']="imgurls";
$z[10][4]['alt']="图片输出区";
$z[11]=Array("field","",2804,2822);
$z[11][4]['name']="body";
$z[12]=Array("field","",2881,2909);
$z[12][4]['name']="caseurl";
$z[13]=Array("prenext","",2967,2992);
$z[13][4]['get']="pre";
$z[14]=Array("prenext","",3001,3027);
$z[14][4]['get']="next";
$z[15]=Array("include","",3144,3181);
$z[15][4]['filename']="footer.htm";

?>