<?php
$z[0]=Array("field","",846,865);
$z[0][4]['name']="title";
$z[1]=Array("global","",866,892);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",937,959);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",1003,1055);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1926,1967);
$z[4][4]['filename']="head_works.htm";
$z[5]=Array("field","",2287,2306);
$z[5][4]['name']="title";
$z[6]=Array("field","",2327,2383);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[7]=Array("field","",2409,2436);
$z[7][4]['name']="phpurl";
$z[8]=Array("field","",2460,2483);
$z[8][4]['name']="id";
$z[9]=Array("field","",2488,2512);
$z[9][4]['name']="mid";
$z[10]=Array("field","\r\n                       <p><img src=\"[field:imgsrc/]\" alt=\"[field:alttext /]\"></p>\r\n					   <br>\r\n					 ",2635,2802);
$z[10][4]['name']="imgurls";
$z[10][4]['alt']="图片输出区";
$z[11]=Array("field","",2825,2843);
$z[11][4]['name']="body";
$z[12]=Array("field","",2902,2930);
$z[12][4]['name']="caseurl";
$z[13]=Array("prenext","",2988,3013);
$z[13][4]['get']="pre";
$z[14]=Array("prenext","",3022,3048);
$z[14][4]['get']="next";
$z[15]=Array("include","",3165,3202);
$z[15][4]['filename']="footer.htm";

?>