<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/141206/1-1412061P040.png ",93,245);
$z[1][4]['ddimg']="/uploads/allimg/141206/1-1412061P040.png";
$z[1][4]['text']="案例";
$z[1][4]['width']="750";
$z[1][4]['height']="1908";

?>