<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150112/1-150112202500.png ",93,240);
$z[1][4]['ddimg']="/uploads/allimg/150112/1-150112202500.png";
$z[1][4]['text']="";
$z[1][4]['width']="656";
$z[1][4]['height']="320";

?>