
<field:full_name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:full_name>

<field:mobile itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mobile>

<field:email itemname="电子邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:company itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>

<field:msg itemname="详情" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:msg>
