<?php
$z[0]=Array("field","",846,865);
$z[0][4]['name']="title";
$z[1]=Array("global","",866,892);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",937,966);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",1010,1069);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2009,2050);
$z[4][4]['filename']="head_works.htm";
$z[5]=Array("channel","\r\n                        <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                        ",2617,2843);
$z[5][4]['type']="sun";
$z[5][4]['currentstyle']="<li class='active'><a href='~typelink~' >~typename~</a></li>";
$z[6]=Array("list","\r\n                        <li>\r\n                            <div class=\"view-tenth\"><img src=\"[field:picname/]\"><a href=\"[field:arcurl/]\" class=\"mask\" target=\"_blank\"><h2>[field:title/]</h2><p>发布于：[field:pubdate function=MyDate('Y-m-d',@me)/] / 浏览：[field:click/]</p></a>\r\n                            </div>\r\n                        </li>\r\n                      ",3003,3428);
$z[6][4]['pagesize']="8";
$z[6][4]['titlelen']="30";
$z[7]=Array("pagelist","",3525,3556);
$z[7][4]['listitem']="pre";
$z[8]=Array("pagelist","",3557,3589);
$z[8][4]['listitem']="next";
$z[9]=Array("include","",3685,3722);
$z[9][4]['filename']="footer.htm";

?>