<?php
$z[0]=Array("field","",819,838);
$z[0][4]['name']="title";
$z[1]=Array("global","",839,865);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",910,939);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",983,1042);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1988,2029);
$z[4][4]['filename']="head_works.htm";
$z[5]=Array("channel","\r\n                        <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                        ",2596,2822);
$z[5][4]['type']="sun";
$z[5][4]['currentstyle']="<li class='active'><a href='~typelink~' >~typename~</a></li>";
$z[6]=Array("list","\r\n                        <li>\r\n                            <div class=\"view-tenth\"><img src=\"[field:picname/]\"><a href=\"[field:arcurl/]\" class=\"mask\" target=\"_blank\"><h2>[field:title/]</h2><p>发布于：[field:pubdate function=MyDate('Y-m-d',@me)/] / 浏览：[field:click/]</p></a>\r\n                            </div>\r\n                        </li>\r\n                      ",2982,3407);
$z[6][4]['pagesize']="8";
$z[6][4]['titlelen']="30";
$z[7]=Array("pagelist","",3504,3535);
$z[7][4]['listitem']="pre";
$z[8]=Array("pagelist","",3536,3568);
$z[8][4]['listitem']="next";
$z[9]=Array("include","",3664,3701);
$z[9][4]['filename']="footer.htm";

?>