<script>
/*
 * 初始化页面
 */
function iniPage_detail() {
	//控制tab标签的diabled
	$('#data_tabs').tabs('enable', 1);
	$('#data_tabs').tabs('select', 1);
	$('#data_tabs').tabs('disable', 0);

	switch ("<?php echo $this->editType;?>") {
		case 'add':
			//使能指定的图片功能
			toggleMenuImg('data_menu', '<?php foreach($this->dataMenuInfo["menutoggle"]["btnAdd"] as $item):?>#<?php echo $item;?>,<?php endforeach;?>');
			
			//修改form的action属性
			$('#data_formDetail').attr('action', "<?php echo $this->baseUrl() . '/' . $this->moduleName . '/' . $this->controllerName . '/' . $this->dataMenuInfo['basemenu']['btnAdd']['actionname'];?>");
			
			//enable输入框
			$('#data_formDetail').find('.data-detail-input').removeAttr('disabled');
			break;
		case 'modify':
			//使能指定的图片功能
			toggleMenuImg('data_menu', '<?php foreach($this->dataMenuInfo["menutoggle"]["btnModify"] as $item):?>#<?php echo $item;?>,<?php endforeach;?>');
			
			//enable输入框
			$('#data_formDetail').find('.data-detail-input').removeAttr('disabled');
			
			//修改form的action属性
			$('#data_formDetail').attr('action', "<?php echo $this->baseUrl() . '/' . $this->moduleName . '/' . $this->controllerName . '/' . $this->dataMenuInfo['basemenu']['btnModify']['actionname'];?>");
			break;
		case 'detail':
			//使能指定的图片功能
			toggleMenuImg('data_menu', '<?php foreach($this->dataMenuInfo["menutoggle"]["btnDetail"] as $item):?>#<?php echo $item;?>,<?php endforeach;?>');
			break;
	}
	
	//设置标签默认值
	if ("<?php echo isset($this->dataDetail);?>") {
		var jsonDataInfo = <?php echo json_encode($this->dataDetail);?>;
		
		// !---------- BEGIN: MODIFY ---------- //
		$('#data_formDetail').find('[name=seq]').val(jsonDataInfo['seq']);
		$('#data_formDetail').find('[name=name]').val(jsonDataInfo['name']);
		$('#data_formDetail').find('[name=value]').val(jsonDataInfo['value']);
		$('#data_formDetail').find('[name=type]').find('option[value=' + jsonDataInfo['type'] + ']').attr('selected', 'selected');
		// !---------- END  : MODIFY ---------- //
	} else {
		// !---------- BEGIN: CUSTOM ---------- //
		// !---------- END  : CUSTOM ---------- //
	}
}

$(document).ready(function() {
	iniPage_detail(); //初始化页面
});
</script>
<style type="text/css">
<!--
.battselect { border: 1px solid #ccc; height:20px;cursor:pointer;}
.ui-widget-content {margin-bottom:5px;}
.ui-widget-content table tbody tr td {padding-bottom:5px;}
.ui-widget-content table tbody tr td input {margin-right:15px;}
.ui-widget-content table tbody tr td label {font-weight:700;color:#000;}
.headlabel {text-align:right;}
-->
</style>

<div>
	<form id="data_formDetail" class="wlz_ajaxForm" ajaxContainer="#data_divList" method="post">
		<input type="hidden" name="keyId" value="<?php echo $this->keyId;?>" />
		<div class="ui-widget-header wiliz-widget-header">数据字典</div>
		<div class="ui-widget-content" style="padding:5px;">
		<table cellspacing="5">
			<tr>
				<td>类型序号:</td>
				<td><input type="text" name="seq" class="data-detail-input wiliz-txt" wlzAuth="txtValEmpty" disabled="disabled" /></td>
			</tr>
			<tr>
				<td>类型名称:</td>
				<td><input type="text" name="name" class="data-detail-input wiliz-txt" wlzAuth="txtValEmpty" disabled="disabled" /></td>
			</tr>
			<tr>
				<td>类型值:</td>
				<td><input type="text" name="value" class="data-detail-input wiliz-txt" wlzAuth="txtValEmpty" disabled="disabled" /></td>
			</tr>
			<tr>
				<td>分类名称:</td>
				<td>
					<select name="type" class="data-detail-input wiliz-slt" wlzAuth="sltNotFirst" disabled="disabled" >
						<option></option>
						<?php echo $this->allGTG;?>
					</select>
				</td>
			</tr>
		</table>
		</div>
	</form>
</div>