<table class="table">

    <tr>

        <th>Title</th>

        <th>Content</th>

        <th>Add news</a></th>

    </tr>

    <?php foreach ($paginator as $news) : ?>

        <tr>

            <td><?php echo $this->escapeHtml($news->username); ?></td>

            <td><?php echo $this->escapeHtml($news->password); ?></td>

            <td>

                <a href="<?php echo $this->url('news', array('action' => 'edit', 'id' => $news->id));?>"><?php echo $this->translate("Edit") ?></a>

                <a href="<?php echo $this->url('news', array('action' => 'delete', 'id' => $news->id));?>"><?php echo $this->translate("Delete") ?></a>

            </td>

        </tr>

    <?php endforeach; ?>

</table>
