<?php $_categories = Mage::helper('catalog/category')->getStoreCategories() ?>
<?php if(count($_categories)): 
    ?>
<div class="navleft-container visible-lg visible-md">
	<?php if(Mage::getStoreConfig('vmegamenu/general/title')){?>
			<div class="megamenu-title"><h2><?php echo Mage::getStoreConfig('vmegamenu/general/title'); ?></h2></div>
		<?php }?>
    <div id="pt_vmegamenu" class="pt_vmegamenu">
        
        <?php
        $showhome = Mage::getStoreConfig('vmegamenu/general/showhome');
        $active = '';
        if(Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms') :
            $active = ' act';
        endif; 
        if($showhome){
            $id     = "_home";
            $html[] = '<div id="pt_menu' . $id . '" class="pt_menu' . $active . '" >';
            $html[] = '<div class="parentMenu">';
            $html[] = '<a href="'.Mage::helper('core/url')->getHomeUrl().'">';
            $html[] = '<span>Home</span>';
            $html[] = '</a>';
            $html[] = '</div>';
            $html[] = '<div class="wrap-popup"><div id="popup' . $id . '" class="popup" >';
            $html[] = '</div>';
            $html[] = '</div>';
            $html[] = '</div>';
            $html = implode("\n", $html);
            echo $html;
        }
	$n = 0;
	foreach ($_categories as $_category):
	$n++;
	endforeach;
	//echo $n;
	
	$i=1;
	$total = count($_categories);
	
        foreach ($_categories as $_category):
	    $class='';
	    if($i==1) $class="first";
	    else if($i==$n) $class="last";
	    echo $this->drawCustomMenuItem($_category,0, false, $class);
	    $i++;
        endforeach ?>
        
        <?php
        //$collection = Mage::getModel('cms/block')->getCollection()
        //            ->addFieldToFilter('identifier', array('like'=>'pt_item_menu'.'%'))
        //            ->addFieldToFilter('is_active', 1);
        //foreach($collection as $key => $value){
        //    $blockId = $value->getIdentifier();
        //    $blockHtml = $this->getLayout()->createBlock('cms/block')->setBlockId($blockId)->toHtml();
        //    if ($blockHtml) echo $this->drawCustomMenuBlock($blockId);
        //}
        
        /*menu links*/
        //$blockLinkId = 'pt_menu_links';
        //$blockLinkHtml = $this->getLayout()->createBlock('cms/block')->setBlockId($blockLinkId)->toHtml();
        //if ($blockLinkHtml){
        //    $id     = "_link";
        //    $htmlLink[] = '<div id="pt_menu' . $id . '" class="pt_menu" >';
        //    $htmlLink[] = '<div class="parentMenu">';
        //    $htmlLink[] = $blockLinkHtml;
        //    $htmlLink[] = '</div>';
        //    $htmlLink[] = '</div>';
        //    $htmlLink = implode("\n", $htmlLink);
        //    echo $htmlLink;
        //}
        ?>
        
        <div class="clearBoth"></div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
var VMEGAMENU_POPUP_EFFECT = <?php echo (int)Mage::getStoreConfig('vmegamenu/popup/effect')?>;
//]]>

$jq(document).ready(function(){
    $jq("#pt_menu_link ul li").each(function(){
        var url = document.URL;
        $jq("#pt_menu_link ul li a").removeClass("act");
        $jq('#pt_menu_link ul li a[href="'+url+'"]').addClass('act');
    }); 
        
    $jq('.pt_menu').hover(function(){
        if(VMEGAMENU_POPUP_EFFECT == 0) $jq(this).find('.popup').stop(true,true).slideDown('slow');
        if(VMEGAMENU_POPUP_EFFECT == 1) $jq(this).find('.popup').stop(true,true).fadeIn('slow');
        if(VMEGAMENU_POPUP_EFFECT == 2) $jq(this).find('.popup').stop(true,true).show('slow');
    },function(){
        if(VMEGAMENU_POPUP_EFFECT == 0) $jq(this).find('.popup').stop(true,true).slideUp('fast');
        if(VMEGAMENU_POPUP_EFFECT == 1) $jq(this).find('.popup').stop(true,true).fadeOut('fast');
        if(VMEGAMENU_POPUP_EFFECT == 2) $jq(this).find('.popup').stop(true,true).hide('fast');
    })
});
</script>

<?php endif ?>
