<?php
$title = $this->getTitle();
$description = $this->getDescription();
$identify = $this->getIdentify();
$categoryIds = $this->getCatIds();
$categoryIds = explode(',', $categoryIds);
$_helper = $this->helper('catalog/output');
$productsOnRow = $this->getProductsOnRow();
$show_price = Mage::getStoreConfig('categorytabs/categorytabs_config/show_price');
$review = Mage::getStoreConfig('categorytabs/categorytabs_config/show_review');
$addtowishlist = Mage::getStoreConfig('categorytabs/categorytabs_config/addtowishlist');
$addtocompare =  Mage::getStoreConfig('categorytabs/categorytabs_config/addtocompare');
$addtocart =  Mage::getStoreConfig('categorytabs/categorytabs_config/addtocart');
if(!$productsOnRow) $productsOnRow = 3;
if ( !$this->getWidthThumbnail() ){
	$w_thumbnail = 135;
} else {
	$w_thumbnail = $this->getWidthThumbnail();
}
if( !$this->getHeightThumbnail() ){
	$h_thumbnail = 135;
 }
else {
	$h_thumbnail = $this->getHeightThumbnail();
}
?>

<div class="container-tab" style="display:none">
	<div class="box-category">
	<div class="tab-title"><?php 	echo '<h2>'.$title.'</h2>'; ?></div>
	<ul class="tabs tabs<?php echo '-'.$identify;?>"> 
		<?php 
		     $k = 0;
		     foreach($categoryIds as $cate_id) {
			     $cate_model = Mage::getModel('catalog/category');
			     $cateName = $cate_model->load($cate_id)->getName();
			     
			     if($cateName) {
		?>
			<li class="<?php if($k==0){ echo "active"; }?>" rel="tab<?php echo $cate_id.'-'.$identify;?>"><?php  echo $cateName; ?></li>
	<?php }  $k++; } ?>
	</ul>
	</div>
	<div class="tab_container"> 
		<?php foreach($categoryIds as $cate_id) { ?>
		 <div id="tab<?php echo $cate_id.'-'.$identify;?>" class="tab_content_<?php echo $identify; ?>"> 
			<?php $_productCollection = $this->getProductCate($cate_id); ?>
			<?php $_collectionSize = $_productCollection->count() ?>
			<?php $_columnCount = $productsOnRow; ?>
		<?php $i=0; foreach ($_productCollection as $_product): ?>
			<?php if ($i++%$_columnCount==0): ?>
			<ul class="products-grid row">
				
			<?php endif ?>
			
				<li class="col-md-4 col-sm-4 col-sms-12 item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
					<div class="item-inner">
						
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail, $h_thumbnail); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
							<div class="box-item">
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
							<?php echo $this->getPriceHtml($_product, true) ?>
							<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							
							<div class="actions">
								<div class="cart-content">
									<?php if($_product->isSaleable()): ?>
										<button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('+ Add to Cart') ?></span></span></button>
									<?php else: ?>
										<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									<?php endif; ?>
									<ul class="add-to-links">
										<?php if($addtowishlist) { ?>
											<?php if ($this->helper('wishlist')->isAllow()) : ?>
												<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('+ Wishlist') ?></a></li>
											<?php endif; ?>
										<?php } ?>
										<?php if($addtocompare) { ?>
											<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
												<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('+ Compare') ?></a></li>
											<?php endif; ?>
										<?php } ?>
									</ul>
								</div>
							</div>
							</div>
					</div>
				</li>
			
			<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
			
			</ul>
			<?php endif ?>
			<?php endforeach ?>
		 </div><!-- #tab1 -->
		 <?php }?>

		 
	 </div> <!-- .tab_container --> 

</div> <!-- #container -->

<script type="text/javascript">

$jq(document).ready(function() {
	
	$jq(".tab_content_<?php echo $identify; ?>").hide();
	$jq(".tab_content_<?php echo $identify; ?>:first").show(); 

	$jq("ul.tabs<?php echo '-'.$identify;?> li").click(function() {
		$jq("ul.tabs<?php echo '-'.$identify;?> li").removeClass("active");
		$jq(this).addClass("active");
		$jq(".tab_content_<?php echo $identify; ?>").hide();
		var activeTab = $jq(this).attr("rel"); 
		$jq("#"+activeTab).fadeIn(); 
	});
});

</script> 
