<script>
/*
 * 获取module下的controller
 */
function getModuleController(obj) {
	var moduleId = $(obj).find('option:selected').attr('moduleId');
	var url = "<?php echo $this->baseUrl() . '/' . $this->moduleName  . '/' . $this->controllerName . '/getmodulecontroller2';?>";
	$('#divController').load(url, {
		'moduleId': moduleId
	});
}

/*
 * 确认排序module
 */
function confirmSortModule(obj) {
	var arrSortInfo = new Array();
	var i = 1;
	$(obj).closest('td').find('.msltList').find('option').each(function() {
		var arrTemp = new Array($(this).val(), i++);
		arrSortInfo.push(arrTemp);
	});
	var url = "<?php echo $this->baseUrl() . '/' . $this->moduleName  . '/' . $this->controllerName . '/confirmsortmodule';?>";
	$('#divModule').load(url, {
		'arrSortInfo': arrSortInfo
	});
}

$(document).ready(function() {
	$('[name=msltModule]').find('option:first').attr('selected', 'selected');
	$('[name=msltModule]').change();
});
</script>
	
<style>
.itemdefine-item {
	padding: 10px;
	margin: 5px;
	text-align: center;
}

.itemdefine-btn {
	width: 160px;
	height: 25px;
	margin-top: 10px;
}
</style>

<div class="ui-state-default itemdefine-item" style="font-weight:bold;">
	<div>
		<input type="button" class="ui-state-default wiliz-cursor-pointer wiliz-btn" value="上移" onclick="moveUpDown(this, 'up');" />
		<input type="button" class="ui-state-default wiliz-cursor-pointer wiliz-btn" value="下移" onclick="moveUpDown(this, 'down');" />
	</div>
	<div><input type="button" class="ui-state-default wiliz-cursor-pointer itemdefine-btn" value="确认提交" onclick="confirmSortModule(this);" /></div>
</div>

<div class="ui-state-default itemdefine-item">
	<select name="msltModule" class="wlz_mslt_sltSingle wiliz-sltl msltList" multiple="multiple" onchange="getModuleController(this);" style="height:300px;">
	<?php if (isset($this->allModule)): ?>
		<?php foreach ($this->allModule as $arrSub): ?>
		<option value="<?php echo $arrSub['itemId'];?>" moduleId="<?php echo $arrSub['moduleId'];?>" ><?php echo $arrSub['displayName'];?></option>
		<?php endforeach; ?>
	<?php endif; ?>
	</select>
</div>