<style type="text/css">
<!--
#lblMenuName {
	background:url(<?php echo $this->baseUrl();?>/img/main/tabbg.png) no-repeat center top;
	position:absolute;
	width:127px;
	height:41px;
	top:50px;
	left:200px;
	line-height:41px;
	text-align:center;
	color:#D2D2D2;
	font-size:15px;
	display:none;
}
-->
</style>
<table class="wlz-table" cellpadding="0" cellspacing="0">
	<!--<tr class="multiTab" style="height:30px;">
		<td class="main-content-top1"><img src="<?php //echo $this->baseUrl();?>/img/main/left-top-right.gif"></td>
		<td class="main-content-top2">
			<table class="main-content-top3" cellpadding="0" cellspacing="0" style="width:100%;">
				<tr><td class="main-content-top4"><label id="lblMenuName"></label></td></tr>
			</table>
		</td>
		<td class="main-content-top5"><img src="<?php echo $this->baseUrl();?>/img/main/nav-right-bg.gif"></td>
	</tr>-->

	<tr style="height:100%;">
		<td class="main-content-middle1">&nbsp;</td>
		<td class="main-content-middle2"><label id="lblMenuName"></label><div id="divContent" style="height:100%;"></div></td>
		<td class="main-content-middle3">&nbsp;</td>
	</tr>

	<!--<tr class="multiTab" style="height:30px;">
		<td class="main-content-bottom1"><img src="<?php //echo $this->baseUrl();?>/img/main/buttom_left2.gif"></td>
		<td class="main-content-bottom2"><img src="<?php //echo $this->baseUrl();?>/img/main/buttom_bgs.gif"></td>
		<td class="main-content-bottom3"><img src="<?php //echo $this->baseUrl();?>/img/main/buttom_right2.gif"></td>
	</tr>-->
</table>