<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" class="no-js">
<head>
<?php require_once 'loadjs.phtml';?>
<script>
/*
 * 获取窗口resize事件
 */
var RESIZE_TIMER = null; //防止重复提交
$(window).resize(function(){
	if (RESIZE_TIMER){
		clearTimeout(RESIZE_TIMER);
	}
	RESIZE_TIMER = setTimeout('setWindowCss()', 50);
});

/*
 * 窗口resize事件调用函数
 */
function setWindowCss() {
	RESIZE_TIMER = null;

	var bodyHeight = $('body').height() - $('#header').height() - $('#footer').height() - 30;
	$('#divMainMenu').height(bodyHeight-60);
}

$(document).ready(function() {
	$(window).resize();
});
</script>
<style type="text/css">
<!--
body {
	font-size: 12px;
	font-family: Arial,Helvetica,sans-serif;
	background:#fff url(<?php echo $this->baseUrl();?>/img/main/bgbg.jpg) no-repeat left top;
}
.backgroundLoad img {
	width:100%;
	height:100%;
	position:absolute;
	top:0;
	left:0;
	z-index:-1;
	display:none;
}
#footer {
	width:100%;
	padding:10px 0;
	background:#000000;
	text-align:left;
	color:#ccc;
	font-size:12px;
}
#footer h5{
	padding-left:10px;
}

#divMainMenu {
	/*background:url(<?php echo $this->baseUrl();?>/img/main/menubg.png) no-repeat left top;*/
	text-align:center;
	padding-top:60px;
}
-->
</style>
</head>

<body>

<div id="divTempContainer"></div>
<div id="divTempDialog"></div>
<div class="backgroundLoad">
<img id="imgHomepageBgPic" src="<?php echo $this->baseUrl();?>/img/main/bgbg.jpg" onload="$(this).hide();$(this).fadeIn('slow');"/>
</div>
<table class="wlz-root wlz-table">
	<tr id="header" style="height:70px;"><td><?php require_once 'header.phtml';?></td></tr>
	<tr id="body"><td>
		<table class="wlz-table"><tr>
			<td style="width:200px;"><div id="divMainMenu" class="main-menu"></div></td>
			<td id="divMainContent"><?php require_once 'content.phtml';?></td>
		</tr>
        </table>
	</td></tr>
    <tr><td><div id="footer">
<h5>版权所有&nbsp;&nbsp;&copy;2013yyd&nbsp;&nbsp;保留所有权力</h5>
</div></td></tr>
</table>
</body>
</html>