<script>

$(document).ready(function() {
	//初始化手风琴
	/*var toggles = document.getElementsByClassName('main-accordion-head');
	var contents = document.getElementsByClassName('main-accordion-body');
	var myAccordion = new fx.Accordion(
		toggles, contents, {opacity: true, duration: 400}
	);
	myAccordion.showThisHideOpen(contents[0]); //content里数字为默认展开第几栏*/

	$('#divMainMenu').find('li').each(function() {
		$(this).bind('click', function() {
			//选中li添加isSelected属性
			$(this).closest('.rootNode').find('li[wlz_selected]').removeClass('wlz_selected');
			$(this).addClass('wlz_selected');

			$('#divMainContent').find('.multiTab:hidden').show();
			var moduleName = $(this).attr('moduleName');
			var controllerName = $(this).attr('controllerName');
			var url = "<?php echo $this->baseUrl();?>/" + moduleName + '/' + controllerName + '/index' + '/avoidCache/' + Math.random();
			if ($(this).attr('isDialog') == 1) {
				$('#divTempContainer').load(url);
			} else {
				var lblText = $(this).find('a').text().padLeft(12, '&nbsp;');
				$('#lblMenuName').html(lblText);
				$('#divContent').load(url);
			}
		});
	});

	$('#divMainMenu').find('ul.main-menu-son').each(function() {
		if ($(this).find('li:visible').length == 0) {
			$(this).closest('.rootNode').hide();
		}
	});

	$('#divMainMenu').find('li:visible:first').click(); return;
});
</script>
<div id="divMainMenu" class="main-menu">
	<table style="width:100%;height:100%;" border="0" cellpadding="0" cellspacing="0" >
		<tr><td style="vertical-align:top;">
			<?php if (isset($this->menuList)): ?>
				<?php foreach($this->menuList as $key=>$arrSub): ?>
				<div class="rootNode">
					<h5 class="main-accordion-head main-menu-parent"><a><?php echo $key; ?></a></h5>
					<div class="main-accordion-body">
						<div>
							<ul class="main-menu-son">
								<?php foreach($arrSub as $arrThird): ?>
								<li id="li<?php echo $arrThird['moduleName'] . $arrThird['controllerName'];?>"
									moduleName="<?php echo $arrThird['moduleName'];?>" controllerName="<?php echo $arrThird['controllerName'];?>"
									<?php if ($arrThird['isDialog']==1):?>isDialog="1"<?php endif;?> <?php if ($arrThird['isMenu']==0):?>style="display:none;"<?php endif;?>>
									<a href="javascript:void(0);"><?php echo $arrThird['itemName'];?></a>
								</li>
								<?php endforeach; ?>
							</ul>
						</div>
					</div>
				</div>
				<?php endforeach; ?>
			<?php endif; ?>
		</td></tr>
	</table>
</div>